spring.application.name=Surit
server.port=8800

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:oracle:thin:@112.221.47.69:10000:xe
spring.datasource.username=C##SURIT_ADMIN
spring.datasource.password=SURIT0820
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver